version: "3.9"
services:
  cars_db:
    container_name: cars_db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cars
      PGDATA: /var/lib/postgresql/data/pgdata
      DB_HOST: 0.0.0.0
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cars_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cars_db:5432/cars
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 127.0.0.1:80:8080
    depends_on:
      - cars_db